server:
  port: 8080

spring:
  application:
    name: jwtdemo-gateway

  cloud:
    gateway:
      routes:
        - id: saloon-api
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
            - AddRequestHeader=X-Gateway-Request, Gateway


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      maximum-expected-value:
        all: 60000
      percentiles:
        all: 0.5, 0.75, 0.95, 0.99
  server:
    port: 18080