### Access using gateway
GET http://localhost:8080/saloon
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaXN0b2xlcm8iLCJyb2xlIjoic2hvb3RlciIsImV4cCI6MTc0ODM1MjcxOH0.Z2oLSM7mW0unJKREXIpeAel32L9mAYZHPFivou8vkJI

### Metrics
GET http://localhost:18080/actuator/metrics/spring.cloud.gateway.requests
