### Access using gateway without host
GET http://localhost:8080/saloon
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaXN0b2xlcm8iLCJyb2xlIjoic2hvb3RlciIsImV4cCI6MTc0NzA0NDg0MX0.gpK2GZCduyEyUA5Sd46bvx4EKlqHjIdgIExzbXiK26w
